<a href="https://colab.research.google.com/github/vishalkumar51095/Aegis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.absolute(-100)

100

In [ ]:
import numpy
numpy.pi

3.141592653589793

Chapter-2: Creating Arrays

In [ ]:
import numpy as np
a=[1,2,3]
arr=np.array(a)
arr

array([1, 2, 3])

In [ ]:
import numpy as np
arr=np.array([1,2,3])
arr          

array([1, 2, 3])

In [ ]:
import numpy as np
a=[]
n=int(input("Enter the size of Array"))
for i in range(n):
  val=int(input("Enter number:"))
  a.append(val)
myarray=np.array(a)
myarray

Enter the size of Array3
Enter number:1
Enter number:2
Enter number:3


array([1, 2, 3])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Dimension of array=",arr.ndim)

Dimension of array= 2


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Shape of array=",arr.shape)

Shape of array= (3, 3)


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
import numpy as np

arr = np.array(42)

arr

array(42)

Chapter 3: Array Indexing

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0]) 

1


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) 

7


Take input from user and Sum of numArray

In [ ]:
import numpy as np
n=int(input("Enter the size of Array:"))
a=[]
for i in range(n):
  val=int(input("Enter numbers:"))
  a.append(val)
arr=np.array(a);
sum=0
for i in range(arr.size):
  sum+=arr[i]
print("Sum of Array:",sum)

Enter the size of Array:3
Enter numbers:3
Enter numbers:4
Enter numbers:5
Sum of Array: 12


Accessing elements from 2d Arrays

In [ ]:
import numpy as np
row=int(input("Enter the number of rows:"))
col=int(input("Enter the number of columns:"))
matrix=[]
for i in range(row):
  a=[]
  for j in range(col):
    val=int(input("Enter number"))
    a.append(val)
  matrix.append(a)
arr=np.array(matrix)
for i in range(row):
  for j in range(col):
    print(arr[i][j],end=" ")
  print()
print(type(arr))

Enter the number of rows:2
Enter the number of columns:2
Enter number1
Enter number2
Enter number3
Enter number4
1 2 
3 4 
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  2


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4]) 

5th element on 2nd row:  10


Accessing elements from 3d Arrays

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) 

6


Negative Indexing

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1]) 
print('Second Last element from 2nd dim: ', arr[1, -2]) 

Last element from 2nd dim:  10
Second Last element from 2nd dim:  9


Chapter 4: Slicing 

Example 1: arr[index:place]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("slice with index 1 to end 5th place:",arr[1:5]) 

slice with index 1 to end 5th place: [2 3 4 5]


Example 2: arr[index:]=arr[index:last place]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:]) 

[5 6 7]


Example 3: arr[:place]=arr[start index:place]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4]) 

[1 2 3 4]


Example 4: Negative Slicing --> arr[-index:-place]=arr[size-index:size-last]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1]) 

[5 6]


Example 5: STEP--> arr[index:last:gap( diff b/w elements of index to last)]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:6:1]) 
print(arr[1:6:2])
print(arr[1:6:3])

[2 3 4 5 6]
[2 4 6]
[2 5]


Slicing 2-D Arrays

Example 1: arr[1, 1:4]=arr[array,index:last]

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) 

[7 8 9]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2]) 

[3 8]


Chapter -NumPy Functions

In [ ]:
import numpy as np
arr=np.zeros(4)
arr

array([0., 0., 0., 0.])

In [ ]:
import numpy as np
arr=np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
import numpy as np
arr=np.ones(3)
arr

array([1., 1., 1.])

In [ ]:
import numpy as np
arr=np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
import numpy as np
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
import numpy as np
arr=np.diag([3,2,1,4])
print("diagonal array\n",arr)
print("diagonal element\n",np.diag(arr))

diagonal array
 [[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 4]]
diagonal element
 [3 2 1 4]


In [ ]:
import numpy as np
arr=np.random.randint(1,10,3)
print("random array\n",arr)

random array
 [9 9 6]


In [ ]:
import numpy as np
arr=np.random.rand(5)
print("random array of 1-D\n",arr)

random array of 1-D
 [0.71275423 0.75059675 0.26325468 0.80370011 0.94904487]


In [ ]:
import numpy as np
arr=np.random.rand(2,5)
print("random array of 2-D\n",arr)

random array of 2-D
 [[0.05010645 0.74024313 0.95214663 0.60730071 0.89079751]
 [0.70763544 0.48892684 0.62070547 0.96382163 0.68315787]]


In [ ]:
import numpy as np
arr=np.random.randn(5)
print("random array cetered to zero\n",arr)

random array cetered to zero
 [2.24484327 1.05244345 0.47472667 0.9442877  0.37575352]
